# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: |
          touch .env
          echo "PHONE_PE_HOST_URL="https://api-preprod.phonepe.com/apis/pg-sandbox"" > .env
          echo "MERCHANT_ID="PGTESTPAYUAT"" >> .env
          echo "SALT_INDEX="1"" >> .env
          echo "PORT="3001"" >> .env
          echo "MONGO_URI="mongodb://admin:Y2wRrSw6kTT0ONt@13.200.211.15:27017/?authMechanism=DEFAULT&authSource=soulMatch"" >> .env
    - run: pm2 restart soulMatchBackend

